# Generated by Django 2.0.3 on 2019-10-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='bills',
            name='quantity',
        ),
    ]
