# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 08:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('universal_billing_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='post_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='merchant',
            name='Business_owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='join_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='industry',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.AlterField(
            model_name='revstreams',
            name='name',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
