# -*- coding: utf-8 -*-
# Generated by Django 1.11.25 on 2019-10-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='pay_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
