# Generated by Django 2.0.3 on 2019-10-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20191008_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='Revstreams',
        ),
        migrations.AddField(
            model_name='merchant',
            name='Revstreams',
            field=models.ManyToManyField(default=None, to='universal_billing_system.Revstreams'),
        ),
    ]
