# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0002_auto_20190929_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='Revstreams',
            new_name='revstream',
        ),
    ]
