# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-29 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0004_bills_business_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bills',
            old_name='business_owner',
            new_name='Business_owner',
        ),
    ]
