# Generated by Django 2.0.3 on 2019-10-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universal_billing_system', '0004_auto_20191004_1724'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsLetterRecipients',
            new_name='BillRecipients',
        ),
    ]
